name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs-version: ['29.3', '30.0']

    steps:
    - uses: actions/checkout@v4

    - name: Setup Emacs
      uses: jcs090218/setup-emacs@master
      with:
        version: ${{ matrix.emacs-version }}

    - name: Run tests
      run: emacs --batch -l ./run-tests.el

    - name: Check byte compilation
      run: emacs --batch -f batch-byte-compile hide-imports-mode.el

    - name: Check package lint
      run: |
        emacs --batch \
          --eval "(require 'package)" \
          --eval "(add-to-list 'package-archives '(\"melpa\" . \"https://melpa.org/packages/\"))" \
          --eval "(package-initialize)" \
          --eval "(package-refresh-contents)" \
          --eval "(package-install 'package-lint)" \
          --eval "(require 'package-lint)" \
          --eval "(package-lint-batch-and-exit)" \
          hide-imports-mode.el
